#By Samthebest999
print("Thanks for using the installer[By Samthebest999] ;)")
bijc=open("banned-ips.json", "w+")
bije=open("banned-ips.json", "a+")
bije.write("[]")
print("Done!")
print("Creating ops.json")
opsjc=open("ops.json", "w+")
opsje=open("ops.json", "a+")
opsje.write("[]")
print("Done!!")
#done with creating ops.json
print("Creating banned-players.json")
bpjc=open("banned-players.json", "w+")
bpje=open("banned-players.json", "a+")
bpje.write("[]")
print("Done")
#done With creating banned-players.json
print("Creating EULA(End User[s] Licence Agreement).txt")
eulac=open("eula.txt", "w+")
eulae=open("eula.txt", "a+")
eulae.write("#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://account.mojang.com/documents/minecraft_eula).")
eulae.write("#Fri Sep 04 11:20:58 CDT 2020")
eulae.write("eula=true")
print("Done!")
#Done!
print("Creating server.properties")
spc=open("server.properties", "w+")
spe=open("server.properties", "a+")
spe.write("#Minecraft server properties")
spe.write("#Fri Sep 04 11:56:03 CDT 2020")
spe.write("enable-jmx-monitoring=false")
spe.write("rcon.port=25575")
spe.write("level-seed=")
spe.write("gamemode=survival")
spe.write("enable-command-block=false")
spe.write("enable-query=false")
spe.write("generator-settings=")
spe.write("level-name=world")
spe.write("motd=A Minecraft Server")
spe.write("query.port=25565")
spe.write("pvp=true")
spe.write("generate-structures=true")
spe.write("difficulty=easy")
spe.write("network-compression-threshold=256")
spe.write("max-tick-time=60000")
spe.write("use-native-transport=true")
spe.write("max-players=20")
spe.write("online-mode=true")
spe.write("enable-status=true")
spe.write("allow-flight=false")
spe.write("broadcast-rcon-to-ops=true")
spe.write("view-distance=10")
spe.write("max-build-height=256")
spe.write("server-ip=")
spe.write("allow-nether=true")
spe.write("server-port=25565")
spe.write("enable-rcon=false")
spe.write("sync-chunk-writes=true")
spe.write("op-permission-level=4")
spe.write("prevent-proxy-connections=false")
spe.write("resource-pack=")
spe.write("entity-broadcast-range-percentage=100")
spe.write("rcon.password=")
spe.write("player-idle-timeout=0")
spe.write("force-gamemode=false")
spe.write("rate-limit=0")
spe.write("hardcore=false")
spe.write("white-list=false")
spe.write("broadcast-console-to-ops=true")
spe.write("spawn-npcs=true")
spe.write("spawn-animals=true")
spe.write("snooper-enabled=true")
spe.write("function-permission-level=2")
spe.write("level-type=default")
spe.write("spawn-monsters=true")
spe.write("enforce-whitelist=false")
spe.write("resource-pack-sha1=")
spe.write("spawn-protection=16")
spe.write("max-world-size=29999984")
print("Done!!!")
print("Creating usercache.json")
ucjc=open("usercache.json", "w+")
ucje=open("usercache.json", "a+")
ucje.write("[]")
print("Done!")
