#By Samthebest999
print("Thanks for using the installer[By Samthebest999] ;)")
bijc=open("banned-ips.json", "w+")
bije=open("banned-ips.json", "a+")
bije.write("[]")
print("Done!")
print("Creating ops.json")
opsjc=open("ops.json", "w+")
opsje=open("ops.json", "a+")
opsje.write("[]")
print("Done!!")
#done with creating ops.json
print("Creating banned-players.json")
bpjc=open("banned-players.json", "w+")
bpje=open("banned-players.json", "a+")
bpje.write("[]")
print("Done")
#done With creating banned-players.json
print("Creating EULA(End User[s] Licence Agreement).txt")
eulac=open("eula.txt", "w+")
eulae=open("eula.txt", "a+")
eulae.write("#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://account.mojang.com/documents/minecraft_eula).")
eulae.write("#Fri Sep 04 11:20:58 CDT 2020")
eulae.write("eula=true")
print("Done!")
